### ISSUE TITLE
Best name for project?

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-incubator/snowplow-processing-manifest#1]
Is `run` a bit batch-oriented? Perhaps load is too loader-specific? Other thoughts?

**Comment by chuwy** [comment]
`processing` I believe is a good fit. It also reflects data-modeling use-case.

**Comment by alexanderdean** [comment]
Yes I like that - it covers any [batch|stream] processing...

**Comment by chuwy** [comment]
Closing.
