### ISSUE TITLE
Add Bintray and Sonatype credentials to .travis.yml

### ISSUE THREAD

**Issue by chuwy** [snowplow-incubator/snowplow-processing-manifest#2]
### Bintray Maven

* `BINTRAY_SNOWPLOW_MAVEN_API_KEY`

### Sonatype

* `SONA_PASS`

Assuming Bintray Maven user and Sonatype user is `snowplow` and we don't want to encrypt it.

Also following entities should be added:

- [x] Add `BINTRAY_SNOWPLOW_MAVEN_USER="deploy-snowplow-maven"` to Travis (unencrypted)
- [x] Add `SONA_USER="snowplow"` to Travis (unencrypted)
- [x] Travis CI project
- [x] Bintray package
- [ ] Maven Central package

**Comment by alexanderdean** [comment]
Added `_SNOWPLOW` into the API Key varname

**Comment by alexanderdean** [comment]
Bintray package is: https://bintray.com/snowplow/snowplow-maven/snowplow-processing-manifest

I believe we have to wait for an initial M1 before we can push the sync button and get Maven Central accepting this package...

**Comment by chuwy** [comment]
Hey @alexanderdean,

I get following messages after publishing:

```
[info] Done packaging.
[info] 	published snowplow-processing-manifest_2.11 to https://api.bintray.com/maven/deploy-snowplow-maven/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1.pom
[info] 	published snowplow-processing-manifest_2.11 to https://api.bintray.com/maven/deploy-snowplow-maven/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1.jar
[info] 	published snowplow-processing-manifest_2.11 to https://api.bintray.com/maven/deploy-snowplow-maven/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1-sources.jar
[info] 	published snowplow-processing-manifest_2.11 to https://api.bintray.com/maven/deploy-snowplow-maven/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1-javadoc.jar
[info] deploy-snowplow-maven/snowplow-processing-manifest@0.1.0-M1 was released
[success] Total time: 106 s, completed Feb 27, 2018 8:17:07 AM
```

and 

```
[error] java.lang.RuntimeException: failed to sync deploy-snowplow-maven/snowplow-processing-manifest@0.1.0-M1 with maven central: {"message":"In order to sync to Maven Central your package must be included in the JCenter repository"}
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at bintray.BintrayRepo.syncMavenCentral(BintrayRepo.scala:153)
```

Also, cannot see files on bintray yet.

**Comment by alexanderdean** [comment]
It's an empty package, so I can't get it added to JCenter yet.

**Comment by chuwy** [comment]
Interesting. It claims that package was published, but still no files...

**Comment by chuwy** [comment]
@alexanderdean maybe we chose wrong `BINTRAY_SNOWPLOW_MAVEN_USER`.  Comparing logs with Scala Tracker:

```
https://api.bintray.com/maven/[secure]/[secure]-maven/[secure]-maven/com/[secure]analytics/[secure]-scala-tracker_2.10/0.5.0/[secure]-scala-tracker_2.10-0.5.0-javadoc.jar
```

```
https://api.bintray.com/maven/deploy-snowplow-maven/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1-sources.jar
```

For me it looks like there's something different in those lines.

**Comment by alexanderdean** [comment]
What is the corresponding *env var* called in the Scala Tracker? Would be surprised if it's called `BINTRAY_SNOWPLOW_MAVEN_USER`

**Comment by chuwy** [comment]
Yes, it is called `BINTRAY_USER`.

**Comment by alexanderdean** [comment]
Then try `BINTRAY_USER="snowplow"`

**Comment by chuwy** [comment]
```
[info] Packaging /home/travis/build/snowplow-incubator/snowplow-processing-manifest/target/scala-2.11/snowplow-processing-manifest_2.11-0.1.0-M1-javadoc.jar ...
[info] Done packaging.
[error] java.lang.RuntimeException: error uploading to https://api.bintray.com/maven/snowplow/maven/maven/com/snowplowanalytics/snowplow-processing-manifest_2.11/0.1.0-M1/snowplow-processing-manifest_2.11-0.1.0-M1.pom: {"message":"This resource requires authentication"}
[error] 	at bintray.BintrayMavenRepository.put(Resolver.scala:54)
```

**Comment by chuwy** [comment]
Though path also doesn't look like one for Scala Tracker.

**Comment by alexanderdean** [comment]
I'd recommend opening up the CI/CD code for another JVM library and this one side-by-side and figuring out what the point of difference is...

**Comment by alexanderdean** [comment]
I think just copy it from @BenFradet's scala-maxmind-iplookups project as that worked smoothly once the Travis and Bintray woes resolved themselves.

**Comment by chuwy** [comment]
Hey @alexanderdean, I think I've managed to publish [M1](https://bintray.com/snowplow/snowplow-maven/snowplow-processing-manifest/0.1.0-M1) on Bintray. Am I right that next step is to enable repository on JCenter?

**Comment by alexanderdean** [comment]
Done, keep me posted.

**Comment by alexanderdean** [comment]
The sync to Maven Central has been done, please confirm everything looks good to you @chuwy
